const productActionTypes = {
	PRODUCT_LIST_REQ: "PRODUCT_LIST_REQ",
	PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
	PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",

	PRODUCT_DETAILS_REQ: "PRODUCT_DETAILS_REQ",
	PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
	PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",

	PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
	PRODUCT_DELETE_REQ: "PRODUCT_DELETE_REQ",
	PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",

	// PRODUCT_CREATE_RESET:"PRODUCT_CREATE_RESET",
	PRODUCT_CREATE_FAIL: "PRODUCT_CREATE_FAIL",
	PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
	PRODUCT_CREATE_REQ: "PRODUCT_CREATE_REQ",

	PRODUCT_UPDATE_REQ: "PRODUCT_UPDATE_REQ",
	PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
	PRODUCT_UPDATE_FAIL: "PRODUCT_UPDATE_FAIL",

	PRODUCT_CREATE_REVIEW_REQ: "PRODUCT_CREATE_REVIEW_REQ",
	PRODUCT_CREATE_REVIEW_SUCCESS: "PRODUCT_CREATE_REVIEW_SUCCESS",
	PRODUCT_CREATE_REVIEW_FAIL: "PRODUCT_CREATE_REVIEW_FAIL",
	PRODUCT_CREATE_REVIEW_RESET: "PRODUCT_CREATE_REVIEW_RESET",

	PRODUCT_TOP_REQ:"PRODUCT_TOP_REQ",
	PRODUCT_TOP_SUCCESS:"PRODUCT_TOP_SUCCESS",
	PRODUCT_TOP_FAIL:"PRODUCT_TOP_FAIL"
};

export default productActionTypes;
