const userActionTypes = {
	USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
	USER_REGISTER_REQ: "USER_REGISTER_REQ",
	USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",

	USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
	USER_LOGIN_REQ: "USER_LOGIN_REQ",
	USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

	USER_LOGOUT: "USER_LOGOUT",

	USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
	USER_DETAILS_REQ: "USER_DETAILS_REQ",
	USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",

	USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
	USER_UPDATE_PROFILE_REQ: "USER_UPDATE_PROFILE_REQ",
	USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",

	USER_LIST_REQ: "USER_LIST_REQ",
	USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
	USER_LIST_FAIL: "USER_LIST_FAIL",

	USER_DELETE_REQ: "USER_DELETE_REQ",
	USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
	USER_DELETE_FAIL: "USER_DELETE_FAIL",

	USER_UPDATE_FAIL:"USER_UPDATE_FAIL",
	USER_UPDATE_SUCCESS:"USER_UPDATE_SUCCESS",
    USER_UPDATE_REQ:"USER_UPDATE_REQ",
    USER_DETAILS_RESET:"USER_DETAILS_RESET"
};

export default userActionTypes;
